In [1]:
import torch

In [2]:
print(torch.tensor([[1, 2], [3, 4]]))  # ------ 2차원 형태의 텐서 생성
print(torch.tensor([[1, 2], [3, 4]], device="cuda:0"))  # ------ GPU에 텐서 생성
print(torch.tensor([[1, 2], [3, 4]], dtype=torch.float64))  # ------ dtype을 이용하여 텐서 생성

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
